[package]
name = "ekbasis-git"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Git CLI wrapper used to create and inspect alternative timelines"
repository.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
