//! `ekbasis ci ...` — GitHub Actions integration and PR workflows.

use anyhow::{Context as _, Result, bail};

use crate::commands::Context;
use crate::output;
use crate::CiInitArgs;

/// `ekbasis ci init` — generates `.github/workflows/ekbasis.yml`.
pub fn init(args: &CiInitArgs, verbose: bool) -> Result<()> {
    let context = Context::load(verbose)?;
    let workflow_dir = context.paths.repo_root().join(".github").join("workflows");
    let workflow_path = workflow_dir.join("ekbasis.yml");

    if workflow_path.exists() && !args.force {
        bail!(
            "`{}` already exists — pass --force to overwrite",
            context.paths.rel(&workflow_path)
        );
    }

    std::fs::create_dir_all(&workflow_dir)
        .with_context(|| format!("cannot create `{}`", workflow_dir.display()))?;

    let repo = args.repo.as_deref().unwrap_or("ekbasis/ekbasis");
    let experiments = args.experiments.as_deref().unwrap_or("all");
    let fail_on_regression = if args.fail_on_regression { "true" } else { "false" };

    let content = format!(
        r#"# Ekbasis pull request benchmark workflow (generated by `ekbasis ci init`).
#
# When a pull request is opened or updated, this workflow runs Ekbasis
# to compare the PR head commit against the base commit and posts
# the benchmark comparison as a pull request comment.

name: Ekbasis PR Benchmark

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write   # needed to post or update the benchmark comment

concurrency:
  group: ekbasis-${{{{ github.event.pull_request.number }}}}
  cancel-in-progress: true

jobs:
  ekbasis:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      # Check out the project under test with full history so Ekbasis can resolve commits.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Check out Ekbasis action toolchain.
      - uses: actions/checkout@v4
        with:
          repository: {repo}
          path: .ekbasis-toolchain
          fetch-depth: 1

      - name: Run Ekbasis Benchmark
        uses: ./.ekbasis-toolchain/.github/actions/ekbasis
        with:
          ekbasis-path: .ekbasis-toolchain
          experiments: {experiments}
          base-ref: ${{{{ github.event.pull_request.base.sha }}}}
          candidate-ref: ${{{{ github.event.pull_request.head.sha }}}}
          iterations: '5'
          warmup: '1'
          fail-on-regression: '{fail_on_regression}'
          comment: 'true'
"#
    );

    std::fs::write(&workflow_path, content)
        .with_context(|| format!("cannot write `{}`", workflow_path.display()))?;

    println!("{}", output::banner("ci init (GitHub Actions)"));
    println!("{}", output::kv("workflow", context.paths.rel(&workflow_path)));
    println!("{}", output::kv("trigger", "pull_request (opened, synchronize, reopened)"));
    println!("{}", output::kv("experiments", experiments));
    println!("{}", output::kv("fail on regression", fail_on_regression));
    println!();
    println!("Commit `{}` and push to enable automatic PR benchmarks.", context.paths.rel(&workflow_path));

    Ok(())
}
